# Generated by Django 5.2.5 on 2025-09-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='abbrev',
            new_name='abrev',
        ),
    ]
