# Generated by Django 5.2.5 on 2025-09-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_abbrev_country_abrev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='abbrev',
            new_name='abrev',
        ),
    ]
